apiVersion: v1
kind: Service
metadata:
  name: swingstate-service-service
spec:
  type: NodePort
  selector:
    app: swingstate
    service: swingstate-service
    deployment: uat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
