apiVersion: apps/v1
kind: Deployment
metadata:
  name: swingstate-deployment
  namespace: project-2-swingstate
  labels: 
    app: swingstate
    service: swingstate-service
    deployment: uat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swingstate
      service: swingstate-service
  template:
    metadata:
      labels:
        app: swingstate
        service: swingstate-service
    spec:
      containers:
      - name: swingstate-app
        image: gcr.io/focal-legacy-279818/swingstate-app:p2
        imagePullPolicy: Always
        env:
        - name: LB_HOST
          value: "35.236.243.7"
        - name: LB_DATABASE
          value: "postgres"
        - name: LB_USER
          value: "postgres"
        - name: LB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: swingstate-secrets
              key: password
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 2020
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 2020
          initialDelaySeconds: 3
          periodSeconds: 3
