version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  build-swingstate:
    docker:
    - image: circleci/node:12.18.2
    steps:
      - checkout
      - run: 
          working_directory: ~/project/Project-2-Swingstate/*
          name: Install
          command: |
            npm install
      - slack/status:
          mentions: 'CHANNEL'
          only_for_branches: 'master'
          success_message: 'The master branch has been updated'
          failure_message: 'You should probably tell Tanique that the code failed'
      - slack/status:
          mentions: 'CHANNEL'
          only_for_branches: 'testing'
          success_message: 'New code is ready for you to pull from testing branch'
          failure_message: 'You should probably tell Tanique that the code failed'
workflows:
    build-and-test:
      jobs:
        - build-swingstate
