version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  build-swingstate:
    docker:
    - image: circleci/node:12.18.2
    steps:
      - checkout
      - run: 
          working_directory: ~/project/Project-2-Swingstate/*
          name: Install
          command: |
            npm install
      - slack/status:
          mentions: 'CHANNEL'
          success_message: 'New code is ready for you to pull in the repository'
          failure_message: 'You should probably tell Tanique that the code failed'
workflows:
    triggers:
        filters:
             branches:
               only:
                 - master
                 - testing
    build-and-test:
      jobs:
        - build-swingstate
