apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server-deployment
  namespace: p2-swingstate
  labels:
    app: swingstate
    service: user-server
    deployment: uat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swingstate
  template:
    metadata:
      labels:
        app: swingstate
        service: user-server
    spec:
      containers:
      - name: user-server
        image: gcr.io/focal-legacy-279818/swingstate-user-service
        imagePullPolicy: Always
        env:
        - name: LB_USER
          value: "postgres"
        - name: LB_DATABASE
          value: "postgres"
        - name: LB_HOST
          value: "35.236.243.7"
        - name: LB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-server-secrets
              key: password
        ports:
        - containerPort: 2020
        livenessProbe:
          httpGet:
            path: /health
            port: 2020
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 2020
          initialDelaySeconds: 3
          periodSeconds: 3