apiVersion: apps/v1
kind: Deployment
metadata:
  name: swingstate-user-service-deployment
  labels:
    app: swingstate
    service: user-service
    deployment: uat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swingstate
  template:
    metadata:
      labels:
        app: swingstate
        service: user-service
    spec:
      containers:
      - name: swingstate-user-service
        image: gcr.io/focal-legacy-279818/swingstate-user-service
        imagePullPolicy: Always
        env:
        - name: LB_USER
          value: "postgres"
        - name: LB_DATABASE
          value: "postgres"
        - name: LB_HOST
          value: "35.236.243.7"
        - name: LB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: swingstate-user-service-secrets
              key: password
        ports:
        - containerPorts: 2020
        livenessProbe:
          httpGet:
            path: /health
            port: 2020
          initialDelaySeconds: 3
          periodSeconds: 3