apiVersion: v1
kind: Service
metadata:
  name: user-server-service
  namespace: p2-swingstate
spec:
  type: ClusterIP
  selector:
    app: swingstate
    service: user-server
    deployment: uat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2020