apiVersion: v1
kind: Service
metadata:
  name: swingstate-user-service-service
spec:
  type: ClusterIP
  selector:
    app: swingstate
    service: user-service
    deployment: uat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2020