apiVersion: apps/v1
kind: Deployment
metadata:
  name: state-server-deployment
  namespace: p2-swingstate
  labels:
    app: swingstate
    service: state-server
    deployment: uat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swingstate
  template:
    metadata:
      labels:
        app: swingstate
        service: state-server
    spec:
      containers:
      - name: state-server
        image: gcr.io/focal-legacy-279818/state-server
        imagePullPolicy: Always
        env:
        - name: LB_HOST
          value: "35.236.243.7"
        - name: LB_DATABASE
          value: "postgres"
        - name: LB_USER
          value: "postgres"
        - name: LB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: state-service-secrets
              key: password
        ports:
        - containerPort: 2021
        livenessProbe:
          httpGet:
            path: /health
            port: 2021
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 2021
          initialDelaySeconds: 3
          periodSeconds: 3